### ISSUE TITLE
how to install BSV compiler

### ISSUE THREAD

**Issue by jangtsekiang** [cambridgehackers/fpgamake#21]
hi, 
how do I install the bsv compiler?

thanks

**Comment by jameyhicks** [comment]
The BSV compiler is unfortunately not free. When you get a license for the BSV compiler you will also get instructions on how to install it.

Academic users can get free licenses: http://bluespec.com/university/

**Comment by jangtsekiang** [comment]
thanks for the link. I'll have a look at it.
